#!/usr/bin/env bash

set -exufo pipefail

src_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

container=
arch=amd64
skip_source=
skip_binary=
build=binary
build_dep_dir=

while [ $# -gt 0 ]; do
	case "$1" in
		--container)
			container="$2"
			shift 2
			;;
		--arch)
			arch="$2"
			shift 2
			;;
		--source-only)
			skip_binary=true
			shift
			;;
		--binary-only)
			skip_source=true
			shift
			;;
		--build)
			build="$2"
			shift 2
			;;
		--build-dependencies)
			build_dep_dir="$2"
			shift 2
			;;
		*)
			break
			;;
	esac
done

dir="$(realpath "$1")"

if [ -z "$container" ]; then
	container="$(cat "$dir/.container")"
fi

if [ -z "$skip_source" ]; then
	podman run --arch "$arch" --rm -v "$src_dir/bin:/opt/package_build/bin" -v "$dir:/opt/package_build/workdir" -w "/opt/package_build/workdir" "$container" /opt/package_build/bin/source
fi
if [ -z "$skip_binary" ]; then
	podman run --arch "$arch" --rm -v "$src_dir/bin:/opt/package_build/bin" -v "$dir:/opt/package_build/workdir" -w "/opt/package_build/workdir" "$container" /opt/package_build/bin/binary "$build"
fi
